/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GovernanceFeedbackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSession"
      | "decryptionCallback"
      | "getEncryptedTotalScore"
      | "getResults"
      | "getSessionCount"
      | "getSessionInfo"
      | "hasMemberSubmitted"
      | "hasSubmitted"
      | "mockDecryptSession"
      | "protocolId"
      | "requestFinalize"
      | "submitFeedback"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackSubmitted"
      | "FinalizeRequested"
      | "Finalized"
      | "SessionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createSession",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMemberSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mockDecryptSession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFinalize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFeedback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSessionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasMemberSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockDecryptSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestFinalize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFeedback",
    data: BytesLike
  ): Result;
}

export namespace FeedbackSubmittedEvent {
  export type InputTuple = [sessionId: BigNumberish, member: AddressLike];
  export type OutputTuple = [sessionId: bigint, member: string];
  export interface OutputObject {
    sessionId: bigint;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeRequestedEvent {
  export type InputTuple = [sessionId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [sessionId: bigint, requestId: bigint];
  export interface OutputObject {
    sessionId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizedEvent {
  export type InputTuple = [
    sessionId: BigNumberish,
    totalScore: BigNumberish,
    feedbackCount: BigNumberish,
    averageScore: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: bigint,
    totalScore: bigint,
    feedbackCount: bigint,
    averageScore: bigint
  ];
  export interface OutputObject {
    sessionId: bigint;
    totalScore: bigint;
    feedbackCount: bigint;
    averageScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionCreatedEvent {
  export type InputTuple = [
    sessionId: BigNumberish,
    proposalTitle: string,
    description: string,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: bigint,
    proposalTitle: string,
    description: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    sessionId: bigint;
    proposalTitle: string;
    description: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceFeedback extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceFeedback;
  waitForDeployment(): Promise<this>;

  interface: GovernanceFeedbackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSession: TypedContractMethod<
    [
      proposalTitle: string,
      description: string,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  getEncryptedTotalScore: TypedContractMethod<
    [sessionId: BigNumberish],
    [string],
    "view"
  >;

  getResults: TypedContractMethod<
    [sessionId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalScore: bigint;
        feedbackCount: bigint;
        averageScore: bigint;
      }
    ],
    "view"
  >;

  getSessionCount: TypedContractMethod<[], [bigint], "view">;

  getSessionInfo: TypedContractMethod<
    [sessionId: BigNumberish],
    [
      [string, string, bigint, bigint, string, boolean, bigint] & {
        proposalTitle: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        creator: string;
        finalized: boolean;
        feedbackCount: bigint;
      }
    ],
    "view"
  >;

  hasMemberSubmitted: TypedContractMethod<
    [sessionId: BigNumberish, member: AddressLike],
    [boolean],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  mockDecryptSession: TypedContractMethod<
    [sessionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestFinalize: TypedContractMethod<
    [sessionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitFeedback: TypedContractMethod<
    [sessionId: BigNumberish, plainScore: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSession"
  ): TypedContractMethod<
    [
      proposalTitle: string,
      description: string,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedTotalScore"
  ): TypedContractMethod<[sessionId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getResults"
  ): TypedContractMethod<
    [sessionId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalScore: bigint;
        feedbackCount: bigint;
        averageScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSessionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSessionInfo"
  ): TypedContractMethod<
    [sessionId: BigNumberish],
    [
      [string, string, bigint, bigint, string, boolean, bigint] & {
        proposalTitle: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        creator: string;
        finalized: boolean;
        feedbackCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasMemberSubmitted"
  ): TypedContractMethod<
    [sessionId: BigNumberish, member: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mockDecryptSession"
  ): TypedContractMethod<[sessionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestFinalize"
  ): TypedContractMethod<[sessionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitFeedback"
  ): TypedContractMethod<
    [sessionId: BigNumberish, plainScore: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeedbackSubmitted"
  ): TypedContractEvent<
    FeedbackSubmittedEvent.InputTuple,
    FeedbackSubmittedEvent.OutputTuple,
    FeedbackSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FinalizeRequested"
  ): TypedContractEvent<
    FinalizeRequestedEvent.InputTuple,
    FinalizeRequestedEvent.OutputTuple,
    FinalizeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Finalized"
  ): TypedContractEvent<
    FinalizedEvent.InputTuple,
    FinalizedEvent.OutputTuple,
    FinalizedEvent.OutputObject
  >;
  getEvent(
    key: "SessionCreated"
  ): TypedContractEvent<
    SessionCreatedEvent.InputTuple,
    SessionCreatedEvent.OutputTuple,
    SessionCreatedEvent.OutputObject
  >;

  filters: {
    "FeedbackSubmitted(uint256,address)": TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
    FeedbackSubmitted: TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;

    "FinalizeRequested(uint256,uint256)": TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;
    FinalizeRequested: TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;

    "Finalized(uint256,uint32,uint256,uint32)": TypedContractEvent<
      FinalizedEvent.InputTuple,
      FinalizedEvent.OutputTuple,
      FinalizedEvent.OutputObject
    >;
    Finalized: TypedContractEvent<
      FinalizedEvent.InputTuple,
      FinalizedEvent.OutputTuple,
      FinalizedEvent.OutputObject
    >;

    "SessionCreated(uint256,string,string,uint64,uint64)": TypedContractEvent<
      SessionCreatedEvent.InputTuple,
      SessionCreatedEvent.OutputTuple,
      SessionCreatedEvent.OutputObject
    >;
    SessionCreated: TypedContractEvent<
      SessionCreatedEvent.InputTuple,
      SessionCreatedEvent.OutputTuple,
      SessionCreatedEvent.OutputObject
    >;
  };
}
